Traceback (most recent call last):
  File "tools/oai-pmh-to-skos/oai-pmh-to-skos.py", line 84, in <module>
    recs = oai.listRecords(metadataPrefix='marc21', set=setname)
  File "/usr/lib/python2.6/site-packages/oaipmh/common.py", line 115, in method
    return obj(self, **kw)
  File "/usr/lib/python2.6/site-packages/oaipmh/common.py", line 110, in __call__
    return bound_self.handleVerb(self._verb, kw)
  File "/usr/lib/python2.6/site-packages/oaipmh/client.py", line 65, in handleVerb
    kw, self.makeRequestErrorHandling(verb=verb, **kw))    
  File "/usr/lib/python2.6/site-packages/oaipmh/client.py", line 269, in makeRequestErrorHandling
    xml = self.makeRequest(**kw)
  File "/usr/lib/python2.6/site-packages/oaipmh/client.py", line 316, in makeRequest
    return retrieveFromUrlWaiting(request)
  File "/usr/lib/python2.6/site-packages/oaipmh/client.py", line 344, in retrieveFromUrlWaiting
    text = f.read()
  File "/usr/lib64/python2.6/socket.py", line 354, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib64/python2.6/httplib.py", line 567, in read
    return self._read_chunked(amt)
  File "/usr/lib64/python2.6/httplib.py", line 612, in _read_chunked
    raise IncompleteRead(''.join(value))
httplib.IncompleteRead: IncompleteRead(417 bytes read)
